#index:
#    path: /
#    controller: App\Controller\DefaultController::index

homepage:
  path: /
  controller: App\Controller\DefaultController::homepage

tasks:
  path: /tasks
  controller: App\Controller\TasksController::tasks